### ISSUE TITLE
429 Too Many Requests from rekor.sigstore.dev/api/v1/log/entries in tests

### ISSUE THREAD

**Issue by vlsi** [sigstore/sigstore-java#228]
**Description**

One of the tests failed in GitHub Actions.

See https://github.com/sigstore/sigstore-java/actions/runs/3449462255/jobs/5757395278#step:6:1985

```
> Task :sigstore-gradle:sigstore-gradle-sign-plugin:test
dev.sigstore.gradle.SigstorePublishSignTest > sign file(String, ConfigurationCache)[1], [1] gradleVersion=7.3, configurationCache=ON failure marker
FAILURE  22.0sec, dev.sigstore.gradle.SigstorePublishSignTest > sign file(String, ConfigurationCache)[1], [1] gradleVersion=7.3, configurationCache=ON
    org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /tmp/junit1001842950044214900 with arguments 
...

    Caused by: com.google.api.client.http.HttpResponseException: 429 Too Many Requests
    POST https://rekor.sigstore.dev/api/v1/log/entries
    <html>
    <head><title>429 Too Many Requests</title></head>
    <body>
    <center><h1>429 Too Many Requests</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>
    
    	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
    	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
    	at dev.sigstore.rekor.client.RekorClient.putEntry(RekorClient.java:89)
    	at dev.sigstore.KeylessSigner.sign(KeylessSigner.java:189)
    	at dev.sigstore.KeylessSigner.signFiles(KeylessSigner.java:234)
    	at dev.sigstore.KeylessSigner.signFile(KeylessSigner.java:252)
    	at dev.sigstore.sign.work.SignWorkAction.execute(SignWorkAction.kt:55)
    	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
    	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
    	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
    	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
    	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
    	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
    	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
    	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.lambda$execute$0(IsolatedClassloaderWorkerFactory.java:57)
    	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
    	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
    	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
    	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
    	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
    	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
    	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
    	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
    	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
    	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
    	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
    	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.execute(IsolatedClassloaderWorkerFactory.java:49)
    	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
    	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
    	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
    	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
    	... 3 more
```

**Comment by loosebazooka** [comment]
@bobcallaway is this still a rekor problem? Did staging get any updates?

**Comment by bobcallaway** [comment]
That looks to be a rate limiting issue based on how many requests are being sent in quick succession. Anyway the HTTP client could implement a backoff?

**Comment by vlsi** [comment]
Looks like https://github.com/sigstore/sigstore-java/pull/28 mended the case
