### ISSUE TITLE
Handle 429 Too Many Requests from Rekor

### ISSUE THREAD

**Issue by vlsi** [sigstore/sigstore-java#327]
**Description**

Apparently, the team behind google-http-java-client does not want to handle 429 by default: https://github.com/googleapis/google-http-java-client/issues?q=429

Stacktrace:

```
Caused by: com.google.api.client.http.HttpResponseException: 429 Too Many Requests
    POST https://rekor.sigstore.dev/api/v1/log/entries
    <html>
    <head><title>429 Too Many Requests</title></head>
    <body>
    <center><h1>429 Too Many Requests</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>
    
    	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
    	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
    	at dev.sigstore.rekor.client.RekorClient.putEntry(RekorClient.java:88)
    	at dev.sigstore.KeylessSigner.sign(KeylessSigner.java:274)
    	at dev.sigstore.KeylessSigner.signFiles(KeylessSigner.java:365)
    	at dev.sigstore.KeylessSigner.signFile(KeylessSigner.java:384)
    	at dev.sigstore.sign.work.SignWorkAction.execute(SignWorkAction.kt:57)
    	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
    	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
    	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
    	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
    	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
    	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
    	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
    	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
    	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
    	at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
    	at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
    	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
    	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
```

**Comment by loosebazooka** [comment]
hrmm, I thought I handled this, but I guess I didn't
