### ISSUE TITLE
GRPC issues.

### ISSUE THREAD

**Issue by loosebazooka** [sigstore/sigstore-java#83]
It seems to help a bit.

Now the error is different:

```
> Task :sigstore-sign-plugin:test
> Task :props

> Task :signFile
Please open the following address in your browser:
  https://oauth2.sigstore.dev/auth/auth?client_id=sigstore&code_challenge=X-T-W1WNvUrTI887KKQIbuohVRnn7OQ-cgpVfFFlRbs&code_challenge_method=S256&redirect_uri=http://localhost:55114/Callback&response_type=code&scope=openid%20email
Attempting to open that address in the default browser now...
result: KeylessSigningResult{digest=61df1427227256b0d75a65ba61fadd3316e5008dbcb55eff3553a73a415ea515, certPath=
X.509 Cert Path: length = 3.
[
=========================================================Certificate 1 start.
[
[
  Version: V3
  Subject: 
  Signature Algorithm: SHA384withECDSA, OID = 1.2.840.10045.4.3.3

  Key:  Sun EC public key, 256 bits
  public x coord: 58810725050983403751526204155717586075603810400900668004812043712607538432390
  public y coord: 106968902165781130315702175379987643026677063152671378535970402174340891005079
  parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
  Validity: [From: Fri Aug 26 20:10:31 MSK 2022,
               To: Fri Aug 26 20:20:31 MSK 2022]
  Issuer: CN=sigstore-intermediate, O=sigstore.dev
  SerialNumber: [    5a057c11 49a74204 72fa5b6b 0bed7f76 01de3e92]

Certificate Extensions: 7
[1]: ObjectId: 1.3.6.1.4.1.11129.2.4.2 Criticality=false
Extension unknown: DER encoded OCTET string =
0000: 04 7C 04 7A 00 78 00 76   00 08 60 92 F0 28 52 FF  ...z.x.v..`..(R.
0010: 68 45 D1 D1 6B 27 84 9C   45 67 18 AC 16 3D C3 38  hE..k'..Eg...=.8
0020: D2 6D E6 BC 22 06 36 6F   72 00 00 01 82 DB 22 40  .m..".6or....."@
0030: C3 00 00 04 03 00 47 30   45 02 21 00 D9 C6 D6 FB  ......G0E.!.....
0040: 1E E8 DA 78 24 D1 B3 A9   3E B6 7E 05 8D 15 AA 73  ...x$...>......s
0050: 20 57 F2 6B F8 C7 51 A5   4B 6D 18 20 02 20 63 BF   W.k..Q.Km. . c.
0060: AC B1 D9 4F D8 E8 2B 9B   70 87 AC A0 FA 7B D6 86  ...O..+.p.......
0070: C8 04 6F C5 E1 ED 04 05   94 1D 12 CB EF B8        ..o...........


[2]: ObjectId: 1.3.6.1.4.1.57264.1.1 Criticality=false
Extension unknown: DER encoded OCTET string =
0000: 04 1B 68 74 74 70 73 3A   2F 2F 61 63 63 6F 75 6E  ..https://accoun
0010: 74 73 2E 67 6F 6F 67 6C   65 2E 63 6F 6D           ts.google.com


[3]: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: DF D3 E9 CF 56 24 11 96   F9 A8 D8 E9 28 55 A2 C6  ....V$......(U..
0010: 2E 18 64 3F                                        ..d?
]
]

[4]: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  codeSigning
]

[5]: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  DigitalSignature
]

[6]: ObjectId: 2.5.29.17 Criticality=true
SubjectAlternativeName [
  RFC822Name: sitnikov.vladimir@gmail.com
]

[7]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: DD D1 89 41 CF 04 E4 E8   82 6A D9 B2 77 68 B1 51  ...A.....j..wh.Q
0010: AC 63 CB E3                                        .c..
]
]

]
  Algorithm: [SHA384withECDSA]
  Signature:
0000: 30 64 02 30 2F 9C CE C0   4E 9A B7 2F 8A C9 9B 52  0d.0/...N../...R
0010: E1 50 5E F5 A2 01 69 08   EB 3D 13 BE 32 D0 E0 52  .P^...i..=..2..R
0020: FC 5B 76 72 33 FC C8 5E   56 E7 25 2C FC 5C 09 41  .[vr3..^V.%,.\.A
0030: D1 7C A9 BA 02 30 52 22   64 A2 20 C4 36 CB DF 88  .....0R"d. .6...
0040: 94 27 10 0D B5 95 62 CF   36 C8 8F F5 30 E4 15 A8  .'....b.6...0...
0050: 06 C8 26 88 37 8D 6B 37   0A 62 02 71 02 EA 05 9C  ..&.7.k7.b.q....
0060: 0B BD AB 03 B6 72                                  .....r

]
=========================================================Certificate 1 end.


=========================================================Certificate 2 start.
[
[
  Version: V3
  Subject: CN=sigstore-intermediate, O=sigstore.dev
  Signature Algorithm: SHA384withECDSA, OID = 1.2.840.10045.4.3.3

  Key:  Sun EC public key, 384 bits
  public x coord: 37106115582151918420212712288227128673473782146923152369857257120619193675329754114997289456449298202582723469750767
....

Exception in thread "grpc-nio-worker-ELG-1-2" java.lang.NoClassDefFoundError: io/grpc/netty/shaded/io/netty/buffer/PoolArena$1
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.freeChunk(PoolArena.java:247)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:430)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:396)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:388)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:254)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:245)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:218)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:533)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:500)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:257)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1039)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: io.grpc.netty.shaded.io.netty.buffer.PoolArena$1
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 15 more
```

_Originally posted by @vlsi in https://github.com/sigstore/sigstore-java/issues/82#issuecomment-1228734123_

**Comment by loosebazooka** [comment]
lets move this to a new discussion

**Comment by vlsi** [comment]
I believe this is fixed in newer GRPC.

Here's Sonatype Lift report for my draft release: https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-149a0d97b89a57-1662122576-156618db864b4ac69d60f55d111c6779

It says there's `[sonatype-2021-0818] CWE-404: Improper Resource Shutdown or Release` in grpc-core.
As I upgrade grpc-core to 1.49.0 the error goes away.

**Comment by loosebazooka** [comment]
yeah, I have renovate bot on, it'll probably update all our deps on saturday or something

**Comment by vlsi** [comment]
Please don't. It would create merge conflicts with https://github.com/sigstore/sigstore-java/pull/98

**Comment by loosebazooka** [comment]
gotcha, it can wait till after a merge

**Comment by vlsi** [comment]
Resolved in https://github.com/sigstore/sigstore-java/pull/105
